name: First_workflow
on: 
  pull_request:
    types:
      - opened

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        run: echo "get code ...."

  second_job:
    runs-on: ubuntu-latest
    needs: first_job
    steps:
      - name: Got code
        run: echo ".... Received"
